### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by famagusta** [ology/Chess-Inspector#1]
Hi,
Could you give the installation instructions in the readme? Specifically for OS X.

Thanks
Robin

**Comment by davidkneely** [comment]
Getting the following errors after running perl Makefile.PL:

Checking if your kit is complete...
Warning: the following files are missing in your kit:
    public/images/Black-to-move.png
    public/images/Starting-Position.png
    public/pgn/kasparov-549.pgn
Please inform the author.
Warning: prerequisite Chess::PGN::Parse 0 not found.
Warning: prerequisite Chess::Pgn 0 not found.
Warning: prerequisite Chess::Rep 0 not found.
Warning: prerequisite Chess::Rep::Coverage 0 not found.
Warning: prerequisite Dancer 1.314 not found.
Warning: prerequisite Dancer::Plugin::DirectoryView 0 not found.
Warning: prerequisite Data::TreeDumper 0 not found.
Warning: prerequisite List::Tuples 0 not found.
Warning: prerequisite Template 0 not found.
Warning: prerequisite YAML 0 not found.
Writing Makefile for Chess::Inspector
Writing MYMETA.yml and MYMETA.json

I have Perl 5, version 18 installed on my linux system. Please advise.

**Comment by ology** [comment]
@famagusta : Done (but the next comment shows that there's something wrong...)

**Comment by ology** [comment]
@davidkneely : Please try the simplified installation instructions in the README.md now.  (Basically, I replaced all the "make stuff" with the `sudo cpan .` command.)

**Comment by famagusta** [comment]
That Worked
