### ISSUE TITLE
Advice for getting this to run on Windows?

### ISSUE THREAD

**Issue by NathanWailes** [ology/Chess-Inspector#3]
Hi! This program looks awesome; I had a similar idea a few years ago but got stuck on simulating the chess board and calculating the possible moves.

I use Windows and tried using MINGW64 to install the program, but got stuck on the cpan step; I think it's not working because MINGW64 doesn't have the 'make' command.

**Comment by ology** [comment]
I was unaware of this message ...for a long time apparently.  Apologies.

Anyway, I do not know what MINGW64 uses for make, maybe nmake? :\
